### ISSUE TITLE
Configs - redesign

### ISSUE THREAD

**Issue by jniznan** [calmrat/metrique#107]
You were talking about replacing JsonConf with something else.
I'm just posting it here so that we don't forget.

**Comment by calmrat** [comment]
yea, we'll use this instead.

https://github.com/emre/kaptan

jsonconf has a few methods that kaptan doesn't have... we'll need to cut those out and put them in utils or directly in the module where they're being used; like 'setup_basic' and a few others. 

Otherwise, kaptan is essentially, just like jsonconf, a fancy dictionary object that knows how to convert from multiple formats to dict.

**Comment by jniznan** [comment]
Kaptan didn't have all the functionality we need. For now we're sticking with jsonconf, which has been moved do metriqueu.
