### ISSUE TITLE
tornado @asyncronous

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#120]
support async requests in tornado

**Comment by engineersamuel** [comment]
Have you considered the potential of supporting Openshift?  If so Openshift primarily supports Flask which is process based.  I've used Tornado Extensively, love it, but there are next to no async Python db libs that would effectively use the async portion.  Since metrique is db heavy, I'm curious what portions will use async.

**Comment by calmrat** [comment]
i have considered it; but haven't given it a go yet. Have you tried Motor? Seems to be a relatively new async tornado+mongodb lib, getting good reviews these days. In the coming weeks, i plan on giving it a spin.

I believe it'll be most useful in enabling (along side a more robust multi-process nginx tornado per core deployment) parallel handling of incoming read/write queries; for any operations which don't cause mongodb to hold a lock anyway.

https://github.com/mongodb/motor/

I'll have to test to see though, to be honest. I doubt it'll hurt, either way :)

**Comment by calmrat** [comment]
deferring for now; taking alternative approach; making it really easy to deploy 2+ instances of metriqued + nginx (1 or 2 instances per core); this is available now in master and seems to work well enough and is simple.
