### ISSUE TITLE
github issues cube

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#64]
eg

https://api.github.com/repos/drpoovilleorg/metrique/issues

**Comment by honzagrec** [comment]
Is it possible to add external (PyPI) dependency?
There's PyGithub module https://github.com/jacquev6/PyGithub which seems to support lots of things - may be easier to additional GitHub functionality for metrique.

But it's some kind of double-edged sword, since we'd not use GitHub API directly, so actual extract would I think be slower (hard to optimise)

Which way do you think we should go?

**Comment by calmrat** [comment]
external dependencies are just fine.

**Comment by calmrat** [comment]
I think PyGithub does call github api directly... or i'm not sure what you mean. Calling Github api is the only way to get data from github, so it's going to be relatively slow compared to pulling data from a DB or something.

+1 to giving it a try.

**Comment by calmrat** [comment]
how's it looking?

**Comment by calmrat** [comment]
first pass; let me know if anyone reviews this :)
